feature:
  - name: NxLargeCliqueSize
  - name: NxLargeCliqueSize

models:
  topkpool:

    - parameterName: ratio
      type: DOUBLE
      maxValue: 0.9
      minValue: 0.1
      scalingType: LINEAR
    
    - parameterName: dropout
      type: DOUBLE
      maxValue: 0.9
      minValue: 0.1
      scalingType: LINEAR
    
    - parameterName: act
      type: CATEGORICAL
      feasiblePoints:
        - leaky_relu
        - relu
        - elu
        - tanh

trainer:
  - parameterName: max_epoch
    type: INTEGER
    maxValue: 300
    minValue: 10
    scalingType: LINEAR
  
  - parameterName: early_stopping_round
    type: INTEGER
    maxValue: 30
    minValue: 10
    scalingType: LINEAR

  - parameterName: lr
    type: DOUBLE
    maxValue: 0.1
    minValue: 0.0001
    scalingType: LOG
  
  - parameterName: weight_decay
    type: DOUBLE
    maxValue: 0.005
    minValue: 0.00005
    scalingType: LOG

  - parameterName: batch_size
    type: INTEGER
    maxValue: 128
    minValue: 48
    scalingType: LINEAR


hpo:
  name: anneal
  max_evals: 10

ensemble:
  name: voting
  size: 2