feature:
  - name: ~ # ~ means None

models:
  gcn:
    - parameterName: num_layers
      type: DISCRETE
      feasiblePoints: '2,3'
    
    - parameterName: hidden
      type: NUMERICAL_LIST
      numericalType: INTEGER
      length: 2
      minValue: [32, 32]
      maxValue: [128, 128]
      cutPara: ["num_layers"]
      cutFunc: "lambda x:x[0] - 1"
      scalingType: LOG
    
    - parameterName: dropout
      type: DOUBLE
      maxValue: 0.8
      minValue: 0.2
      scalingType: LINEAR
    
    - parameterName: act
      type: CATEGORICAL
      feasiblePoints:
        - leaky_relu
        - relu
        - elu
        - tanh

trainer:
  - parameterName: max_epoch
    type: INTEGER
    maxValue: 300
    minValue: 100
    scalingType: LINEAR
  
  - parameterName: early_stopping_round
    type: INTEGER
    maxValue: 30
    minValue: 10
    scalingType: LINEAR

  - parameterName: lr
    type: DOUBLE
    maxValue: 0.01
    minValue: 0.001
    scalingType: LOG
  
  - parameterName: weight_decay
    type: DOUBLE
    maxValue: 0.01
    minValue: 0.001
    scalingType: LOG

hpo:
  name: random
  max_evals: 10

ensemble:
  name: ~