# search space for graphsage on cora, citeseer, pubmed
feature:
  - name: PYGNormalizeFeatures

models:
  gcn:
    - parameterName: num_layers
      type: DISCRETE
      feasiblePoints: '2,3'
    
    - parameterName: hidden
      type: NUMERICAL_LIST
      numericalType: INTEGER
      length: 2
      minValue: [16,64]
      maxValue: [16,64]
      cutPara: ["num_layers"]
      cutFunc: "lambda x:x[0] - 1"
      scalingType: LOG
    
    - parameterName: dropout
      type: DOUBLE
      maxValue: 0.8
      minValue: 0.2
      scalingType: LINEAR

    - parameterName: agg, 
      type: CATEGORICAL,
      feasiblePoints": 
        - mean
        - add
        - max
    
    - parameterName: act
      type: CATEGORICAL
      feasiblePoints:
        - leaky_relu
        - relu
        - elu
        - tanh

trainer:
  - parameterName: max_epoch
    type: INTEGER
    maxValue: 200
    minValue: 100
    scalingType: LINEAR
  
  - parameterName: early_stopping_round
    type: INTEGER
    maxValue: 30
    minValue: 10
    scalingType: LINEAR

  - parameterName: lr
    type: DOUBLE
    maxValue: 0.05
    minValue: 0.01
    scalingType: LOG
  
  - parameterName: weight_decay
    type: DOUBLE
    maxValue: 0.001
    minValue: 0.0001
    scalingType: LOG

hpo:
  name: esgd
  max_gen: 2
  sgd_steps: 5
  pps: 10
  ops: 5
  elite_num: 5
  subset_rate: 10
  need_split_dataset: True



ensemble:
  name: ~