# search space for gcn on cora, citeseer, pubmed
feature:
  - name: PYGNormalizeFeatures

models:
  gcn:
    - parameterName: num_layers
      type: DISCRETE
      feasiblePoints: '2'
    
    - parameterName: hidden
      type: NUMERICAL_LIST
      numericalType: INTEGER
      length: 1
      minValue: [32]
      maxValue: [128]
      cutPara: ["num_layers"]
      cutFunc: "lambda x:x[0] - 1"
      scalingType: LOG
    
    - parameterName: dropout
      type: DOUBLE
      maxValue: 0.8
      minValue: 0.2
      scalingType: LINEAR
    
    - parameterName: act
      type: CATEGORICAL
      feasiblePoints:
        - leaky_relu
        - relu
        - elu
        - tanh

trainer:
  - parameterName: max_epoch
    type: INTEGER
    maxValue: 200
    minValue: 100
    scalingType: LINEAR
  
  - parameterName: early_stopping_round
    type: INTEGER
    maxValue: 30
    minValue: 10
    scalingType: LINEAR

  - parameterName: lr
    type: DOUBLE
    maxValue: 0.05
    minValue: 0.005
    scalingType: LOG
  
  - parameterName: weight_decay
    type: DOUBLE
    maxValue: 0.0005
    minValue: 0.00005
    scalingType: LOG

hpo:
  name: moeapri
  max_gen: 20
  sgd_steps: 40
  pps: 40
  ops: 20
  elite_num: 10
  subset_rate: 10
  need_split_dataset: True

ensemble:
  name: ~