# search space for gat on cora, citeseer, pubmed
feature:
  - name: PYGNormalizeFeatures

models:
  gat:

    - parameterName: num_layers
      type: DISCRETE
      feasiblePoints: '2'
  
    - parameterName: heads
      type: DISCRETE
      feasiblePoints: '6,8,10,12'

    - parameterName: hidden
      type: NUMERICAL_LIST
      numericalType: INTEGER
      length: 1
      minValue: [4]
      maxValue: [16]
      cutPara: ["num_layers"]
      cutFunc: "lambda x:x[0] - 1"
      scalingType: LOG
    
    - parameterName: dropout
      type: DOUBLE
      maxValue: 0.8
      minValue: 0.2
      scalingType: LINEAR
    
    - parameterName: act
      type: CATEGORICAL
      feasiblePoints:
        - leaky_relu
        - relu
        - elu
        - tanh

trainer:
  - parameterName: max_epoch
    type: INTEGER
    maxValue: 300
    minValue: 100
    scalingType: LINEAR
  
  - parameterName: early_stopping_round
    type: INTEGER
    maxValue: 30
    minValue: 10
    scalingType: LINEAR

  - parameterName: lr
    type: DOUBLE
    maxValue: 0.05
    minValue: 0.01
    scalingType: LOG
  
  - parameterName: weight_decay
    type: DOUBLE
    maxValue: 0.001
    minValue: 0.0001
    scalingType: LOG

hpo:
  name: anneal
  max_evals: 10000

ensemble:
  name: ~